-- Supabase Database Schema for Rossbets Quant Engine

-- 1. Games Table
CREATE TABLE IF NOT EXISTS games (
    id TEXT PRIMARY KEY,
    sport TEXT NOT NULL,
    home_team TEXT,
    away_team TEXT,
    commence_time TIMESTAMPTZ,
    status TEXT DEFAULT 'upcoming',
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Odds Snapshots Table
CREATE TABLE IF NOT EXISTS odds_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id TEXT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    market_type TEXT NOT NULL,
    bookmaker TEXT NOT NULL,
    outcome TEXT NOT NULL,
    price REAL NOT NULL,
    point REAL,
    player TEXT,
    snapshot_time TIMESTAMPTZ DEFAULT now()
);

-- 3. Analysis Results Table
CREATE TABLE IF NOT EXISTS analysis_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id TEXT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    market_type TEXT NOT NULL,
    outcome TEXT NOT NULL,
    player TEXT,
    true_prob REAL,
    market_prob REAL,
    edge REAL,
    confidence REAL,
    recommended_bet TEXT,
    best_price REAL,
    best_bookmaker TEXT,
    kelly_fraction REAL DEFAULT 0,
    kelly_amount REAL DEFAULT 0,
    ev_pct REAL DEFAULT 0,
    signal_breakdown JSONB,
    reasoning TEXT,
    analyzed_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(game_id, market_type, outcome, player)
);

-- 4. Indexes for Performance Optimization
CREATE INDEX IF NOT EXISTS idx_analysis_game ON analysis_results(game_id);
CREATE INDEX IF NOT EXISTS idx_analysis_edge ON analysis_results(edge);
CREATE INDEX IF NOT EXISTS idx_odds_game ON odds_snapshots(game_id, market_type);

-- 5. App Users Table (Custom Auth)
CREATE TABLE IF NOT EXISTS app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Insert default users (storing passwords as plaintext for simplicity, but in production use bcrypt)
INSERT INTO app_users (username, password_hash) VALUES ('admin', 'admin') ON CONFLICT (username) DO NOTHING;
INSERT INTO app_users (username, password_hash) VALUES ('rosso', 'Jack6') ON CONFLICT (username) DO NOTHING;
